#!/bin/bash

ROOTFS=""
CC="gcc"
EXTRA_CFLAGS=""
LD="ld"
EXTRA_LDFLAGS=""
EXTRA_LIBS=""

make "ROOTFS=${ROOTFS}" "CC=${CC}" "EXTRA_CFLAGS=${EXTRA_CFLAGS}" "LD=${CC}" "EXTRA_LDFLAGS=${EXTRA_LDFLAGS}" "EXTRA_LIBS=${EXTRA_LIBS}"
